developer = "Marvin Ruder <marvin.ruder@liberale-gamer.gg>"
vorsitz = "Franziska Seitz <franziska.seitz@liberale-gamer.gg>"
vorstand = "vorstand@liberale-gamer.gg"
mitgliederbetreuung = "Marvin Ruder <marvin.ruder@liberale-gamer.gg>"
mitgliederbetreuung_mitgliedsantrag = "Marvin Ruder"
it = "it@liberale-gamer.gg"